const initialFleet = [
    { id: 'v1', name: 'Pro2 bleu', type: 'scooter', rate: 100, unit: 5, billingType: 'timer', img: 'images/scooter1.jpg', status: 'available', color: '#007bff' },
    { id: 'v2', name: 'M365 srira', type: 'scooter', rate: 100, unit: 5, billingType: 'timer', img: 'images/scotore2.jpg', status: 'available', color: '#dc3545' },
    { id: 'v3', name: 'Kuiok wheel', type: 'scooter', rate: 100, unit: 5, billingType: 'timer', img: 'images/scooter3.jpg', status: 'available', color: '#845019' },
    { id: 'v4', name: 'ninbut g30 max', type: 'scooter', rate: 100, unit: 5, billingType: 'timer', img: 'images/scooter4.jpg', status: 'available', color: '#dc35b5' },
    { id: 'v5', name: 'pro2 chakib', type: 'scooter', rate: 100, unit: 5, billingType: 'timer', img: 'images/scooter5.jpg', status: 'available', color: '#28a745' },
];

const translations = {
    ar: {
        appTitle: "إدارة أسطول EV",
        availableFleet: "الأسطول المتاح",
        activeSession: "الجلسات الحالية",
        history: "سجل التأجير",
        analytics: "الإحصائيات",
        fleet: "الأسطول",
        rental: "التأجير",
        rentNow: "تأجير الآن",
        endSession: "إنهاء",
        exportCSV: "تصدير CSV",
        enterPin: "أدخل رقم PIN (الافتراضي: 1234):",
        unlock: "فتح",
        totalRevenue: "إجمالي الإيرادات",
        mostUsed: "الأكثر استخداماً",
        close: "إغلاق",
        available: "متاح",
        busy: "مشغول",
        rentAmount: "المبلغ (DA):",
        rentTime: "الوقت / جولات:",
        startRental: "بدء التأجير",
        scanQr: "امسح الكود لمتابعة الوقت",
        timeRemaining: "الوقت المتبقي",
        tour: "جولة",
        min: "دقيقة"
    },
    en: {
        appTitle: "EV Fleet Manager",
        availableFleet: "Available Fleet",
        activeSession: "Active Sessions",
        history: "Rental History",
        analytics: "Analytics",
        fleet: "Fleet",
        rental: "Rental",
        rentNow: "Rent Now",
        endSession: "End",
        exportCSV: "Export CSV",
        enterPin: "Enter PIN (Default: 1234):",
        unlock: "Unlock",
        totalRevenue: "Total Revenue",
        mostUsed: "Most Used",
        close: "Close",
        available: "Available",
        busy: "Busy",
        rentAmount: "Amount (DA):",
        rentTime: "Time / Tours:",
        startRental: "Start Rental",
        scanQr: "Scan to track time",
        timeRemaining: "Time Remaining",
        tour: "Tour",
        min: "Min"
    }
};